server:
  servlet:
    context-path: /cs
  address: localhost
  port: 8080

app:
  name: cs
  rsa:
    private-key: classpath:private.pem
    public-key: classpath:public.pem
  jwt:
    accessTokenExpirySeconds: 31536000

spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    name: raceappdb
    url: jdbc:mariadb://localhost:3306/raceappdb?sslMode=disable&allowPublicKeyRetrieval=true
    username: dev_raceapp
    password: dev_raceapp!
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer